# Generated by Django 2.2 on 2019-04-15 06:31

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190407_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='email',
            field=models.EmailField(blank=True, default='record@example.com', max_length=254, validators=[main.validators.validate_no_plus_in_email], verbose_name='Дата изменения'),
        ),
    ]
